---
booktitle: Proceedings of The 1st Symposium on Advances in Approximate Bayesian Inference
shortname: AABI
volume: 96
year: '2018'
start: 2018-12-02
end: 2018-12-02
published: 2019-01-05
url: http://proceedings.mlr.press
location: "Le 1000 Conference Center, Montréal, QC H3B 0A2, Canada"
layout: proceedings
series: Proceedings of Machine Learning Research
id: AABI-2018
month: 0
cycles: false
bibtex_editor: Ruiz, Francisco and Zhang, Cheng and Liang, Dawen and Bui, Thang
editor:
- given: Francisco
  family: Ruiz
- given: Cheng
  family: Zhang
- given: Dawen
  family: Liang
- given: Thang
  family: Bui
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 1st Symposium on Advances in Approximate Bayesian Inference on 2nd December 2018 at 
  Le 1000 Conference Center, Montréal, QC H3B 0A2, Canada

  Published as Volume 96 by the Proceedings of Machine Learning Research on 05 January 2019.

  Volume Edited by:
    Francisco Ruiz
    Cheng Zhang
    Dawen Liang
    Thang Bui

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 02 Dec
baseurl: "/v96"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v96
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Symposium on Advances in Approximate Bayesian Inference
  url: 
  location: ''
  dates:
  - 2018-12-02
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from /Users/neil/mlresearch/v96/aabi18.bib
