---
booktitle: Proceedings of The 1st Symposium on Advances in Approximate Bayesian Inference
shortname: AABI
volume: 96
year: '2018'
start: 2018-12-02
end: 2018-12-02
published: 2019-01-05
url: http://proceedings.mlr.press
author:
  name: PMLR
location: Le 1000 Conference Center, Montréal, QC H3B 0A2, Canada
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: AABI-2018
month: 0
cycles: false
bibtex_editor: Ruiz, Francisco and Zhang, Cheng and Liang, Dawen and Bui, Thang
editor:
- given: Francisco
  family: Ruiz
- given: Cheng
  family: Zhang
- given: Dawen
  family: Liang
- given: Thang
  family: Bui
title: Proceedings of Machine Learning Research
description: "Proceedings of The 1st Symposium on Advances in Approximate Bayesian
  Inference on 2nd December 2018 at \nLe 1000 Conference Center, Montréal, QC H3B
  0A2, Canada\n\nPublished as Volume 96 by the Proceedings of Machine Learning Research
  on 05 January 2019.\n\nVolume Edited by:\n  Francisco Ruiz\n  Cheng Zhang\n  Dawen
  Liang\n  Thang Bui\n\nSeries Editors:\n  Neil D. Lawrence\n  Mark Reid\n"
date_str: 02 Dec
baseurl: "/v96"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v96
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Symposium on Advances in Approximate Bayesian Inference
  url: 
  location: ''
  dates:
  - 2018-12-02
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
