---
booktitle: Proceedings of The 1st Symposium on Advances in Approximate Bayesian Inference
shortname: AABI
volume: 96
year: '2018'
start: 2018-12-02
end: 2018-12-02
published: 2019-01-05
url: http://proceedings.mlr.press
location: !binary |-
  TGUgMTAwMCBDb25mZXJlbmNlIENlbnRlciwgTW9udHLpYWwsIFFDIEgzQiAwQTIsIENhbmFkYQ==
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: AABI-2018
month: 0
cycles: false
bibtex_editor: Ruiz, Francisco and Zhang, Cheng and Liang, Dawen and Bui, Thang
editor:
- given: Francisco
  family: Ruiz
- given: Cheng
  family: Zhang
- given: Dawen
  family: Liang
- given: Thang
  family: Bui
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 1st Symposium on Advances in Approximate Bayesian Inference on 02 December 2018

  Published as Volume 96 by the Proceedings of Machine Learning Research on 05 January 2019.

  Volume Edited by:
    Francisco Ruiz
    Cheng Zhang
    Dawen Liang
    Thang Bui

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 02 Dec
baseurl: "/v96"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v96
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Symposium on Advances in Approximate Bayesian Inference
  url: 
  location: ''
  dates:
  - 2018-12-02
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
